percentage_vol_target: 20
notional_trading_capital: 10000
base_currency: "USD"
trading_rules:
  ewmac16_64:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults
     data: data.daily_prices
     other_args: 
         Lfast: 16
         Lslow: 64
     forecast_scalar: 4.73
  ewmac64_256:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults
     other_args: 
         Lfast: 64
         Lslow: 256
     forecast_scalar: 1.88
forecast_weights:
     ewmac16_64: 0.5
     ewmac64_256: 0.5
forecast_div_multiplier: 1.1
instrument_weights:
     FXE: .25
     GLD: .25
     IEF: .25
     SPY: .25
instrument_div_multiplier: 1.5
