#YAML
percentage_vol_target: 20
notional_trading_capital: 10000
base_currency: "USD"
trading_rules:
  ewmac8:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults
     data: data.daily_prices
     other_args: 
         Lfast: 8
         Lslow: 32
     forecast_scalar: 5.3
  ewmac32:
     function: systems.provided.example.rules.ewmac_forecast_with_defaults
     other_args: 
         Lfast: 32
         Lslow: 128
     forecast_scalar: 2.65
forecast_weights:
     ewmac8: 0.50
     ewmac32: 0.50
forecast_div_multiplier: 1.1
instrument_weights:
     FXE: .25
     GLD: .25
     IEF: .25
     SPY: .25
instrument_div_multiplier: 1.5

use_forecast_scale_estimates: True
